version: '2'
services:
  web:
    restart: always
    build: .
    command: node public/index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /mnt/md0:/mnt/md0

    ports:
      - "8064:8000"
